SkillsGuide/urls.py
"""
SkillsGuide URL Configuration
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from . import sitemaps, views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("saml2/", include(("djangosaml2.urls", "saml2"), namespace="saml2")),
    path(
        "sitemap.xml",
        sitemap,
        {
            "sitemaps": {
                "static": sitemaps.StaticViewSitemap,
                "chapters": sitemaps.ChapterSitemap,
                "articles": sitemaps.ArticleSitemap,
            }
        },
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("clinical_traineeship_checklist/", views.ClinicalTraineeshipChecklistView.as_view(), name="clinical_traineeship_checklist"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<str:slug>/", views.ChapterDetailView.as_view(), name="chapter-detail"),
    path("<str:chapter>/<str:slug>", views.ArticleDetailView.as_view(), name="article-detail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

SkillsGuide/models.py
import logging
import magic
import mimeparse

from django.db import models
from django.dispatch import receiver
from django.urls import reverse_lazy as reverse
from django.utils.translation import gettext_lazy as _
from colorfield.fields import ColorField
from django_extensions.db.models import TimeStampedModel
from django_extensions.db.fields import AutoSlugField
from ordered_model.models import OrderedModel
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField

from .conf import settings
from .utils import Uuid4Upload

logger = logging.getLogger(__name__)


class CompetenceLevel(OrderedModel):
    title = models.CharField(_("Title"), max_length=256)
    acronym = models.CharField(_("Acronym"), max_length=6)
    slug = AutoSlugField(populate_from=["title"])

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.title


class Chapter(OrderedModel):
    title = models.CharField(_("Title"), max_length=256)
    image = models.ImageField(upload_to=Uuid4Upload)
    dark = ColorField()
    light = ColorField()
    slug = AutoSlugField(populate_from=["title"])

    tags = TaggableManager(blank=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('chapter-detail', kwargs={'slug': self.slug})


class Section(OrderedModel):
    chapter = models.ForeignKey("Chapter", on_delete=models.CASCADE)
    title = models.CharField(_("Title"), max_length=256)
    slug = AutoSlugField(populate_from=["title"])

    order_with_respect_to = "chapter"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        path = self.chapter.get_absolute_url()
        return f"{path}#{self.slug}"


class Article(OrderedModel):
    section = models.ForeignKey("Section", on_delete=models.CASCADE)
    competence_level = models.ForeignKey("CompetenceLevel", on_delete=models.CASCADE)
    title = models.CharField(_("Title"), max_length=256)
    description = RichTextField(_("Description"))
    revision = models.BooleanField(_("Revision"), default=False)
    slug = AutoSlugField(populate_from=["title"])

    order_with_respect_to = "section"

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article-detail', kwargs={'chapter': self.section.chapter.slug, "slug": self.slug})


class Source(models.Model):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    authors = models.TextField()
    title = models.TextField()
    published = models.TextField()


class Image(models.Model):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    description = models.TextField(_("Description"))
    file = models.ImageField(upload_to=Uuid4Upload)


class Card(OrderedModel):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    description = models.TextField(_("Description"))
    image = models.ImageField(upload_to=Uuid4Upload, blank=True, null=True)

    order_with_respect_to = "article"

    class Meta(OrderedModel.Meta):
        pass


class Video(models.Model):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    description = models.TextField(_("Description"))
    file = models.FileField(upload_to=Uuid4Upload)


class Download(TimeStampedModel):
    title = models.CharField(max_length=128)
    description = RichTextField()
    active = models.BooleanField(default=True, verbose_name=_("Active"))
    top = models.BooleanField(default=False, verbose_name=_("Top-Download"))
    file = models.FileField(upload_to="uploads/")
    icon = models.TextField(default="file-o")

    class Meta:
        verbose_name = _("Download")
        verbose_name_plural = _("Downloads")

    def __str__(self):
        return self.title

    @staticmethod
    @receiver(models.signals.pre_save, sender="SkillsGuide.Download")
    def pre_save(sender, instance, raw, **kwargs):
        icons = {
            ("audio",): "file-audio-o",
            ("image",): "file-image-o",
            ("video",): "file-video-o",
            ("text",): "file-text-o",
            ("application", "pdf"): "file-pdf-o",
            ("application", "zip"): "file-archive-o",
        }
        instance.file.seek(0)
        mimetype = magic.from_buffer(instance.file.read(2048), mime=True)
        instance.file.seek(0)
        maintype, subtype, _ = mimeparse.parse_mime_type(mimetype)
        instance.icon = icons.get((maintype, subtype), icons.get((maintype,), "file-o"))


class Text(OrderedModel):

    HOMEPAGE = "homepage"
    ABOUT = "about"
    CLINICAL_TRAINEESHIP_CHECKLIST = "clinical_traineeship_checklist"
    PLACEMENT_CHOICES = (
        (HOMEPAGE, _("Homepage")),
        (ABOUT, _("About us")),
        (CLINICAL_TRAINEESHIP_CHECKLIST, _("Clinical traineeship checklist")),
    )

    title = models.CharField(max_length=128)
    body = RichTextField()
    placement = models.CharField(
        max_length=32,
        choices=PLACEMENT_CHOICES,
        default=HOMEPAGE,
    )
    order_with_respect_to = "placement"

    class Meta:
        verbose_name = _("Text")
        verbose_name_plural = _("Texts")

    def __str__(self):
        return f"{self.title} ({self.placement})"


class Slide(OrderedModel):
    title = models.CharField(max_length=128)
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to=Uuid4Upload)

    class Meta(OrderedModel.Meta):
        verbose_name = _("Slide")
        verbose_name_plural = _("Slides")

    def __str__(self):
        return self.title


class News(TimeStampedModel):
    title = models.CharField(max_length=128)
    body = RichTextField()
    datetime = models.DateTimeField(auto_now_add=True)
    active = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")
        ordering = ("-datetime",)

    def __str__(self):
        return self.title

SkillsGuide/templates/SkillsGuide/article/detail.html
{% extends "SkillsGuide/content.html" %}

{% load static %}
{% load i18n %}

{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static "lightbox2/css/lightbox.css" %}" type="text/css" charset="utf-8">
{% endblock %}

{% block script %}
<script src="{% static "lightbox2/js/lightbox.js" %}"></script>
{% endblock %}

{% block content %}
<main role="main" class="container">
<section class="row p-3 bg-primary text-white">
  <h1 class="col-md">
    {{ object.section.title }}
    <p class="lead">
      {{ object.title }}
      <span class="badge badge-dark">{{ article.competence_level }}</span>
    </p>
  </h1>
  <div class="col-md-4">
    <div class="btn-group float-right mt-2" role="group">
      <a class="btn btn-dark btn-md" href="{% url "chapter-detail" slug=object.section.chapter.slug %}#{{ object.section.slug }}">
        <i class="fa fa-arrow-left" aria-hidden="true"></i>
        {{ object.section.chapter.title }}
      </a>
    </div>
  </div>
</section>
<hr>
<section class="row mb-4">
  <div class="col">
    {{ object.description|safe }}
  </div>
</section>
{% if object.card_set.exists %}
<section class="row mb-4">
  <div class="col">
    <h4 class="bg-light p-3" id="images">
      <i class="fa fa-book" aria-hidden="true"></i>
      {% trans "Cards" %}
      <a href="#images" class="text-dark float-right">
        <i class="fa fa-link" aria-hidden="true"></i>
      </a>
    </h4>
    <div class="card-group">
      {% for card in object.card_set.all %}
      <div class="card">
        <div class="card-header">
          {{ forloop.counter }}
        </div>
        <div class="card-body">
          <small class="text-muted">{{ card.description }}</small>
        </div>
        {% if card.image %}
        <a href="{{ card.image.url }}" data-lightbox="cards" data-title="{{ card.description }}">
          <img class="card-img-top" src="{{ card.image.url }}" alt="{{ card.description }}">
        </a>
        {% endif %}
      </div>
      {% if not forloop.last %}
      <div class="w-100 d-none d-sm-block d-md-none"><!-- wrap every 1 on sm--></div>
      {% if forloop.counter|divisibleby:3 %}
      <div class="w-100 d-none d-md-block d-lg-none"><!-- wrap every 3 on md--></div>
      {% endif %}
      {% if forloop.counter|divisibleby:4 %}
      <div class="w-100 d-none d-lg-block"><!-- wrap every 4 on lg--></div>
      {% endif %}
      {% endif %}
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}
{% if object.image_set.exists %}
<section class="row mb-4">
  <div class="col">
    <h4 class="bg-light p-3" id="images">
      <i class="fa fa-book" aria-hidden="true"></i>
      {% trans "Images" %}
      <a href="#images" class="text-dark float-right">
        <i class="fa fa-link" aria-hidden="true"></i>
      </a>
    </h4>
    <div class="card-group">
      {% for image in object.image_set.all %}
      <div class="card card-4">
        <a href="{{ image.file.url }}" data-lightbox="images" data-title="{{ image.description }}">
        <img class="card-img-top" src="{{ image.file.url }}" alt="{{ image.description }}">
        </a>
        <div class="card-body">
          <small class="text-muted">{{ image.description }}</small>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}
{% if object.video_set.exists %}
<section class="row mb-4">
  <div class="col">
    <h4 class="bg-light p-3" id="videos">
      <i class="fa fa-book" aria-hidden="true"></i>
      {% trans "Videos" %}
      <a href="#videos" class="text-dark float-right">
        <i class="fa fa-link" aria-hidden="true"></i>
      </a>
    </h4>
    <div class="card-group">
      {% for video in object.video_set.all %}
      <div class="card card-4">
        <video class="card-img-top" controls>
          <source src="{{ video.file.url }}" type="video/mp4">
        </video>
        <div class="card-body">
          <small class="text-muted">{{ video.description }}</small>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}
{% if object.source_set.exists %}
<section class="row">
  <div class="col">
    <h4 class="bg-light p-3" id="sources">
      <i class="fa fa-book" aria-hidden="true"></i>
      {% trans "Sources" %}
      <a href="#sources" class="text-dark float-right">
        <i class="fa fa-link" aria-hidden="true"></i>
      </a>
    </h4>
    <ul>
      {% for source in object.source_set.all %}
      <li>
        <strong>{{ source.authors }}</strong>
        <em>{{ source.title }}</em>
        {{ source.published }}
      </li>
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}
</main>
{% endblock %}