SkillsGuide/urls.py
"""
SkillsGuide URL Configuration
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from . import sitemaps, views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("saml2/", include(("djangosaml2.urls", "saml2"), namespace="saml2")),
    path(
        "sitemap.xml",
        sitemap,
        {
            "sitemaps": {
                "static": sitemaps.StaticViewSitemap,
                "chapters": sitemaps.ChapterSitemap,
                "articles": sitemaps.ArticleSitemap,
            }
        },
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("clinical_traineeship_checklist/", views.ClinicalTraineeshipChecklistView.as_view(), name="clinical_traineeship_checklist"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<str:slug>/", views.ChapterDetailView.as_view(), name="chapter-detail"),
    path("<str:chapter>/<str:slug>", views.ArticleDetailView.as_view(), name="article-detail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

SkillsGuide/models.py
import logging
import magic
import mimeparse

from django.db import models
from django.dispatch import receiver
from django.urls import reverse_lazy as reverse
from django.utils.translation import gettext_lazy as _
from colorfield.fields import ColorField
from django_extensions.db.models import TimeStampedModel
from django_extensions.db.fields import AutoSlugField
from ordered_model.models import OrderedModel
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField

from .conf import settings
from .utils import Uuid4Upload

logger = logging.getLogger(__name__)


class CompetenceLevel(OrderedModel):
    title = models.CharField(_("Title"), max_length=256)
    acronym = models.CharField(_("Acronym"), max_length=6)
    slug = AutoSlugField(populate_from=["title"])

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.title


class Chapter(OrderedModel):
    title = models.CharField(_("Title"), max_length=256)
    image = models.ImageField(upload_to=Uuid4Upload)
    dark = ColorField()
    light = ColorField()
    slug = AutoSlugField(populate_from=["title"])

    tags = TaggableManager(blank=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('chapter-detail', kwargs={'slug': self.slug})


class Section(OrderedModel):
    chapter = models.ForeignKey("Chapter", on_delete=models.CASCADE)
    title = models.CharField(_("Title"), max_length=256)
    slug = AutoSlugField(populate_from=["title"])

    order_with_respect_to = "chapter"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        path = self.chapter.get_absolute_url()
        return f"{path}#{self.slug}"


class Article(OrderedModel):
    section = models.ForeignKey("Section", on_delete=models.CASCADE)
    competence_level = models.ForeignKey("CompetenceLevel", on_delete=models.CASCADE)
    title = models.CharField(_("Title"), max_length=256)
    description = RichTextField(_("Description"))
    revision = models.BooleanField(_("Revision"), default=False)
    slug = AutoSlugField(populate_from=["title"])

    order_with_respect_to = "section"

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article-detail', kwargs={'chapter': self.section.chapter.slug, "slug": self.slug})


class Source(models.Model):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    authors = models.TextField()
    title = models.TextField()
    published = models.TextField()


class Image(models.Model):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    description = models.TextField(_("Description"))
    file = models.ImageField(upload_to=Uuid4Upload)


class Card(OrderedModel):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    description = models.TextField(_("Description"))
    image = models.ImageField(upload_to=Uuid4Upload, blank=True, null=True)

    order_with_respect_to = "article"

    class Meta(OrderedModel.Meta):
        pass


class Video(models.Model):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    description = models.TextField(_("Description"))
    file = models.FileField(upload_to=Uuid4Upload)


class Download(TimeStampedModel):
    title = models.CharField(max_length=128)
    description = RichTextField()
    active = models.BooleanField(default=True, verbose_name=_("Active"))
    top = models.BooleanField(default=False, verbose_name=_("Top-Download"))
    file = models.FileField(upload_to="uploads/")
    icon = models.TextField(default="file-o")

    class Meta:
        verbose_name = _("Download")
        verbose_name_plural = _("Downloads")

    def __str__(self):
        return self.title

    @staticmethod
    @receiver(models.signals.pre_save, sender="SkillsGuide.Download")
    def pre_save(sender, instance, raw, **kwargs):
        icons = {
            ("audio",): "file-audio-o",
            ("image",): "file-image-o",
            ("video",): "file-video-o",
            ("text",): "file-text-o",
            ("application", "pdf"): "file-pdf-o",
            ("application", "zip"): "file-archive-o",
        }
        instance.file.seek(0)
        mimetype = magic.from_buffer(instance.file.read(2048), mime=True)
        instance.file.seek(0)
        maintype, subtype, _ = mimeparse.parse_mime_type(mimetype)
        instance.icon = icons.get((maintype, subtype), icons.get((maintype,), "file-o"))


class Text(OrderedModel):

    HOMEPAGE = "homepage"
    ABOUT = "about"
    CLINICAL_TRAINEESHIP_CHECKLIST = "clinical_traineeship_checklist"
    PLACEMENT_CHOICES = (
        (HOMEPAGE, _("Homepage")),
        (ABOUT, _("About us")),
        (CLINICAL_TRAINEESHIP_CHECKLIST, _("Clinical traineeship checklist")),
    )

    title = models.CharField(max_length=128)
    body = RichTextField()
    placement = models.CharField(
        max_length=32,
        choices=PLACEMENT_CHOICES,
        default=HOMEPAGE,
    )
    order_with_respect_to = "placement"

    class Meta:
        verbose_name = _("Text")
        verbose_name_plural = _("Texts")

    def __str__(self):
        return f"{self.title} ({self.placement})"


class Slide(OrderedModel):
    title = models.CharField(max_length=128)
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to=Uuid4Upload)

    class Meta(OrderedModel.Meta):
        verbose_name = _("Slide")
        verbose_name_plural = _("Slides")

    def __str__(self):
        return self.title


class News(TimeStampedModel):
    title = models.CharField(max_length=128)
    body = RichTextField()
    datetime = models.DateTimeField(auto_now_add=True)
    active = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")
        ordering = ("-datetime",)

    def __str__(self):
        return self.title

SkillsGuide/templates/SkillsGuide/about.html
{% extends "SkillsGuide/content.html" %}

{% load static %}
{% load i18n %}
{% load imagekit %}

{% block content %}
<main role="main" class="container">
<div class="row">
  <div class="col-sm">
    {% for text in texts %}
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{{ text.title }}</h3>
        <p class="card-text">{{ text.body|safe }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</main>
{% endblock %}

SkillsGuide/templates/SkillsGuide/base.html
<!doctype html>
{% load static %}
{% load i18n %}
{% load compress %}
{% load analytical %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    {% analytical_head_top %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static "SkillsGuide/favicon.svg" %}">
    {% compress css %}
    <link rel="stylesheet" href="{% static "fonts-fork-awesome/scss/fork-awesome.scss" %}" type="text/x-scss" charset="utf-8">
    {% block style %}
    <link rel="stylesheet" href="{% static "SkillsGuide/style.scss" %}" type="text/x-scss" charset="utf-8">
    {% endblock %}
    {% endcompress %}
    <title>{% trans "Graz Skills Guide" %}</title>
    {% analytical_head_bottom %}
  </head>
  <body>
    {% analytical_body_top %}
    {% block body %}{% endblock %}
      <div class="position-fixed language-selector btn-group dropup d-none d-sm-block">
        <button type="button" class="btn btn-outline-light btn-block dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-language" aria-hidden="true"></i>
          <span class="d-none d-md-inline">
            {% trans "Language" %}
          </span>
        </button>
        <div class="dropdown-menu">
          {% for code, title in LANGUAGES %}
          <a class="dropdown-item" href="?language={{ code }}">
            {{ title }}
          </a>
          {% endfor %}
        </div>
      </div>
    {% compress js %}
    <script src="{% static "jquery/jquery.js" %}"></script>
    <script src="{% static "popper/popper.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap.js" %}"></script>
    {% block script %}{% endblock %}
    <script src="{% static "SkillsGuide/global.js" %}"></script>
    {% endcompress %}
    {% analytical_body_bottom %}
  </body>
</html>

SkillsGuide/templates/SkillsGuide/clinical_traineeship_checklist.html
{% extends "SkillsGuide/content.html" %}

{% load static %}
{% load i18n %}
{% load imagekit %}

{% block content %}
<main role="main" class="container">
<section class="row">
  <h1 class="col-md">
    {% trans "Clinical traineeships checklist" %}
  </h1>
</section>
<section class="row">
  <div class="col-md">
  {% for text in texts %}
  {{ text.body|safe }}
  {% endfor %}
  </div>
</section>
{% if clinical_traineeship_checklist|length > 0 %}
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
  {% for activity in clinical_traineeship_checklist.values %}
  {% if activity.skills|length %}
  <div class="col mb-3">
    <div class="card h-100">
      <div class="card-header">
        {{ activity.name }}
      </div>
      <div class="card-body">
        {% for skill in activity.skills %}
        <a href="{{ skill.target }}" class="btn btn-primary btn-block">{{ skill.name }}</a>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% else %}
<div class="alert alert-primary" role="alert">
  <i class="fa fa-info-circle" aria-hidden="true"></i>
  {% trans "No activities or skills could be imported from LZK." %}
</div>
{% endif %}
</main>
{% endblock %}

SkillsGuide/templates/SkillsGuide/content.html
{% extends "SkillsGuide/base.html" %}

{% load static %}
{% load i18n %}

{% block body %}
<nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white">
  <div class="container">
    <a class="navbar-brand" href="/">
      <i class="fa fa-home fa-2x" aria-hidden="true"></i>
    </a>
    <div class="d-xl-none">
      {% trans "Graz Skills Guide" %}
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-column align-items-start ml-lg-2 ml-0" id="navbarCollapse">
      <div class="d-none d-xl-flex justify-content-center w-100">
        <h2 id="title">
        {% trans "Graz Skills Guide" %}
        </h2>
      </div>
      <div class="navbar-nav flex-row mb-md-1 mt-md-0 mb-3 mt-2 w-100">
        <ul class="navbar-nav mr-auto my-auto">
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownDownloadLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-graduation-cap d-none d-xl-inline" aria-hidden="true"></i>
              {% trans "Chapters" %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownDownloadLink">
              {% for chapter in chapters %}
              <a class="dropdown-item" href="{% url "chapter-detail" slug=chapter.slug %}">
                <i class="fa fa-book" aria-hidden="true"></i>
                {{ chapter.title }}
              </a>
              {% endfor %}
            </div>
          </div>
          {% if top_downloads|length > 0 %}
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownDownloadLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-download d-none d-xl-inline" aria-hidden="true"></i>
              {% trans "Downloads" %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownDownloadLink">
              {% for download in top_downloads %}
              <a class="dropdown-item" href="{{ download.file.url }}">
                <i class="fa fa-{{ download.icon }}" aria-hidden="true"></i>
                {{ download.title }}
              </a>
              {% endfor %}
            </div>
          </div>
          {% endif %}
        </ul>
        <div class="btn-group">
          <form class="form-inline btn mt-2 mt-md-0" action="{% url "search" %}">
            <div class="input-group">
              <input type="text" class="form-control" name="q" placeholder="{% trans "Search" %}" aria-label="{% trans "Search" %}" aria-describedby="nav-button-search">
              <div class="input-group-append">
                <button class="btn btn-outline-light" type="submit" id="nav-button-search">
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>
              </div>
            </div>
          </form>
          {% if user.is_authenticated %}
          <div class="dropdown btn">
            <a class="dropdown-toggle btn btn-outline-light my-2 my-sm-0" href="#" id="navbarDropdownUserLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-user-circle" aria-hidden="true"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownUserLink">
              {% if user.is_staff %}
              <a class="dropdown-item" href="{% url 'admin:index' %}">
                <i class="fa fa-cogs" aria-hidden="true"></i>
                {% trans "Administration" %}
              </a>
              {% endif %}
              <a class="dropdown-item" href="{{ logout_url }}">
                <i class="fa fa-sign-out" aria-hidden="true"></i>
                {% trans "Logout" %}
              </a>
            </div>
          </div>
          {% else %}
          <div class="btn">
            <a class="btn btn-outline-light my-2 my-sm-0" href="{{ login_url }}">
              <i class="fa fa-sign-in" aria-hidden="true"></i>
              {% trans "Login" %}
            </a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<footer class="footer">
  <div class="container">
    <span class="text-muted">
      &copy; {% now "Y" %} {{ copyright }} | <a href="{% url "about" %}">{% trans "About us" %}</a>
    </span>
  </div>
</footer>
{% endblock %}

SkillsGuide/templates/SkillsGuide/index.html
{% extends "SkillsGuide/content.html" %}

{% load static %}
{% load i18n %}
{% load imagekit %}

{% block content %}
<main role="main" class="container">
<div class="row mt-2 d-none d-md-block">
  <div id="carousel" class="carousel slide col-md" data-ride="carousel">
    <ol class="carousel-indicators">
      {% for slide in slides %}
      <li data-target="#carousel" data-slide-to="{{ forloop.counter0 }}"{% if forloop.first %} class="active"{% endif %}></li>
      {% endfor %}
    </ol>
    <div class="carousel-inner">
      {% for slide in slides %}
      <div class="carousel-item{% if forloop.first %} active{% endif %}">
        {% generateimage 'SkillsGuide:slide' source=slide.image as si %}
        <img class="d-block w-100" src="{{ si.url }}" alt="{{ slide.title }}">
        <div class="carousel-caption d-none d-md-block">
          <h5>{{ slide.title }}</h5>
        </div>
      </div>
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">{% trans "Previous" %}</span>
    </a>
    <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">{% trans "Next" %}</span>
    </a>
  </div>
</div>
<div class="row mt-2">
  <div class="col-sm">
    {% for text in texts %}
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{{ text.title }}</h3>
        <p class="card-text">{{ text.body|safe }}</p>
      </div>
    </div>
    {% endfor %}
    {% for entry in news %}
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{{ entry.title }} <small class="float-sm-right text-muted">{{ entry.datetime }}</small></h3>
        <p class="card-text">{{ entry.body }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="col-sm-4">
    {% for chapter in chapters %}
    <a href="{{ chapter.get_absolute_url }}" class="text-decoration-none text-black">
      <div class="card mb-3 chapter-{{ chapter.pk }}">
        <div class="row no-gutters">
          <div class="col-md-4 mx-auto">
            <img src="{{ chapter.image.url }}" class="card-img mw-100 mt-3 mb-3 px-3" alt="{{ chapter.title }}">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ chapter.title }}</h5>
              <p class="card-text">
              <small class="text-muted">
                {% for section in chapter.section_set.all %}
                {{ section.title }}{% if not forloop.last %} | {% endif %} 
                {% endfor %}
              </small>
              </p>
            </div>
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
    {% for download in downloads %}
      <div class="card mb-3">
        <div class="row no-gutters">
          <div class="col-md-4 d-flex justify-content-center my-auto">
            <a href="{{ download.file.url }}" target="_blank" class="text-decoration-none">
              <i class="fa fa-download fa-5x" aria-hidden="true"></i>
            </a>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ download.title }}</h5>
              <p class="card-text">
              {{ download.body }}
              <small class="text-muted">
                <i class="fa fa-link" aria-hidden="true"></i>
                {{ download.file.size|filesizeformat }}
              </small>
              </p>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
</main>
{% endblock %}

SkillsGuide/templates/SkillsGuide/search.html
{% extends "SkillsGuide/content.html" %}

{% load i18n %}

{% block content %}
<main role="main" class="container">
<section class="row">
  <h1 class="col-md">
    {% blocktrans with count=paginator.count query=query %}
    {{ count }} results for "{{ query}}"
    {% endblocktrans %}
  </h1>
</section>
{% if query %}
<div class="list-group">
{% for result in object_list %}
  <a href="{{ result.object.get_absolute_url }}" class="list-group-item list-group-item-action">
    {{ result.object }}
    <span class="badge badge-primary badge-pill float-right chapter-{{ result.chapter }}">
      {{ result.verbose_name }}
    </span>
    {% if result.rendered %}
    <p>
    <small class="text-muted">{{ result.rendered }}</small>
    </p>
    {% endif %}
  </a>
{% empty %}
<div class="alert alert-primary" role="alert">
  <i class="fa fa-info-circle" aria-hidden="true"></i>
  {% trans "No results found." %}
</div>
{% endfor %}
</div>
{% if page_obj.has_previous or page_obj.has_next %}
<div>
  {% if page_obj.has_previous %}<a href="?q={{ query }}&amp;page={{ page_obj.previous_page_number }}">{% endif %}&laquo; Previous{% if page_obj.has_previous %}</a>{% endif %}
  |
  {% if page_obj.has_next %}<a href="?q={{ query }}&amp;page={{ page_obj.next_page_number }}">{% endif %}Next &raquo;{% if page_obj.has_next %}</a>{% endif %}
</div>
{% endif %}

{% else %}
{# Show some example queries to run, maybe query syntax, something else? #}
{% endif %}
</main>
{% endblock %}

SkillsGuide/templates/SkillsGuide/table.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="table table-hover" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead {{ table.attrs.thead.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <th {{ column.attrs.th.as_html }}>
                        {% if column.orderable %}
                            <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                        {% else %}
                            {{ column.header }}
                        {% endif %}
                    </th>
                {% endfor %}
                </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            {% if table.has_footer %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
            </tfoot>
            {% endif %}
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}

    {% block pagination %}
        {% if table.page and table.paginator.num_pages > 1 %}
        <nav aria-label="Table navigation">
            <ul class="pagination justify-content-center">
            {% if table.page.has_previous %}
                {% block pagination.previous %}
                <li class="previous page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                        {% trans 'previous' %}
                    </a>
                </li>
                {% endblock pagination.previous %}
            {% endif %}
            {% if table.page.has_previous or table.page.has_next %}
            {% block pagination.range %}
            {% for p in table.page|table_page_range:table.paginator %}
                <li class="page-item{% if table.page.number == p %} active{% endif %}">
                    <a class="page-link" {% if p != '...' %}href="{% querystring table.prefixed_page_field=p %}"{% endif %}>
                        {{ p }}
                    </a>
                </li>
            {% endfor %}
            {% endblock pagination.range %}
            {% endif %}
            {% if table.page.has_next %}
                {% block pagination.next %}
                <li class="next page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link">
                        {% trans 'next' %}
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endblock pagination.next %}
            {% endif %}
            </ul>
        </nav>
        {% endif %}
    {% endblock pagination %}
</div>
{% endblock table-wrapper %}